version: '3'
services:
  api:
    container_name: nest-api-starter
    restart: always
    build: ./
    ports:
      - '8080:8080'
    links:
      - mongo
    env_file:
      - ./.env.development
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    expose:
      - 27018
    ports:
      - '27018:27017'
